SELECT
	[Abbreviation], [FullName], [Access], [Email], [UserType]
FROM (VALUES
('8', '86db6384-2da3-43e1-a0d7-feee86684aaa', 'Contributor', '', 'User'),
('AD', 'Achutha, Dwarakesh', 'Admin', '', 'User'),
('AS', 'Adarsha Shetty', 'Viewer', '', 'User'),
('AY', 'Ashutosh Yadav', 'Contributor', 'AYadav@foresters.com', 'User'),
('BK', 'Balaraman, Kesavan', 'Viewer', '', 'User'),
('CC', 'Christine Chaisson', 'Contributor', 'CChaisson@foresters.com', 'User'),
('DP', 'Dan Patrichi', 'Admin (Owner)', 'DPatrichi@foresters.com', 'User'),
('FS', 'Fahaduddin Hussaini Syed', 'Contributor', 'FHussainiSyed@foresters.com', 'User'),
('GV', 'Gokhan Varol', 'Admin', 'GVarol@foresters.com', 'User'),
('GD', 'Gupta, Deepak', 'Viewer', '', 'User'),
('IC', 'Iftikhar Choudhary', 'Viewer', 'IChoudhary@foresters.com', 'User'),
('JK', 'Jena, Pabitra Kumar', 'Viewer', '', 'User'),
('JF', 'Jennifer Foo', 'Viewer', 'JFoo@foresters.com', 'User'),
('JN', 'Jha, Nihal', 'Viewer', '', 'User'),
('KI', 'Karl Ishak', 'Admin', 'KIshak@foresters.com', 'User'),
('LM', 'Luke McGrath', 'Contributor', 'LMcGrath@foresters.com', 'User'),
('MR', 'Mahamad, Ruhulla', 'Viewer', '', 'User'),
('M3', 'Membership 360-PROD', 'Admin', '', 'User'),
('M', 'Membership360-Prod-CI-Admin', 'Admin', '', 'Group'),
('M', 'Membership360-Prod-CI-Contributor', 'Contributor', '', 'Group'),
('M', 'Membership360-Prod-CI-Viewer', 'Viewer', '', 'Group'),
('MK', 'M, Suresh Kumar', 'Viewer', '', 'User'),
('PP', 'Pratik Peters', 'Viewer', 'PPeters@foresters.com', 'User'),
('PP', 'Puvvada, Pushpavalli', 'Viewer', '', 'User'),
('RG', 'Raja Govindarajan', 'Viewer', 'raja.govindarajan@foresters.onmicrosoft.com', 'User'),
('RM', 'Ravi Teja Madala', 'Viewer', '', 'User'),
('RS', 'Rish Singh', 'Contributor', 'RSingh@foresters.com', 'User'),
('RP', 'Robert Procopio', 'Viewer', 'RProcopio@foresters.com', 'User'),
('RK', 'Rob Kruse', 'Admin', 'RKruse@foresters.com', 'User'),
('RP', 'Ronit Patel', 'Admin', 'RPatel@foresters.com', 'User'),
('SC', 'Saba Cheema', 'Viewer', 'SCheema@foresters.com', 'User'),
('SS', 'Senguttuvan, Saranya', 'Contributor', 'saranya.senguttuvan@cgi.com', 'User'),
('SN', 'Stephanie Ni', 'Viewer', 'SNi@foresters.com', 'User'),
('SS', 'Sujith Kumar Sukumaran', 'Viewer', 'sujithkumar.sukumaran@cgi.com', 'User'),
('TG', 'Tarun, Golla', 'Viewer', '', 'User'),
('UK', 'Upjeet Kaur', 'Admin', 'UKaur@foresters.com', 'User'),
('VP', 'Venkata Sudheer Padavala', 'Viewer', 'venkata.padavala@cgi.com', 'User'))
vdata ([Abbreviation], [FullName], [Access], [Email], [UserType])
